### ISSUE TITLE
NPE when launch_details is not present and the error occurs for timer execution after maximum retry.

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#376]
logger: com.drajer.ecrapp.config.TaskConfiguration
   message: Error in completing the Execution of Task for EICRTask_MATCH_TRIGGER_1752672_d493b670-c698-4ab1-94f1-0946b5a0843f, Launch Id 1752672, removing the timer after 1314 retriesjava.lang.NullPointerException: null
	at com.drajer.eca.model.MatchTriggerAction.execute(MatchTriggerAction.java:135)
	at com.drajer.ecrapp.service.WorkflowService.executeActions(WorkflowService.java:215)
	at com.drajer.ecrapp.service.WorkflowService.executeActionsForType(WorkflowService.java:230)
	at com.drajer.ecrapp.service.WorkflowService.executeScheduledAction(WorkflowService.java:248)
	at com.drajer.ecrapp.config.TaskConfiguration.lambda$sampleOneTimeTask$0(TaskConfiguration.java:64)
	at com.github.kagkarlsson.scheduler.task.helper.Tasks$OneTimeTaskBuilder$1.executeOnce(Tasks.java:139)
	at com.github.kagkarlsson.scheduler.task.helper.OneTimeTask.execute(OneTimeTask.java:37)
	at com.github.kagkarlsson.scheduler.Scheduler$PickAndExecute.executePickedExecution(Scheduler.java:352)
	at com.github.kagkarlsson.scheduler.Scheduler$PickAndExecute.runButLogExceptions(Scheduler.java:328)
	at com.github.kagkarlsson.scheduler.concurrent.LoggingRunnable.run(LoggingRunnable.java:28)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by AnanthaKrishnaV** [comment]
Fixed with PR #378
