### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException while process telecom data, when telecom value is lesser then 10 characters 

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [drajer-health/eCRNow#377]
java.lang.StringIndexOutOfBoundsException while process telecom data, when telecom value is lesser then 10 characters .
exception: String index out of range: 6
   logger: com.drajer.ecrapp.config.TaskConfiguration
   message: Error in completing the Execution of Task for EICRTask_CLOSE_OUT_EICR_1880470_a1849366-4d3c-4ac9-9597-32d2c1e477b5, Launch Id 1880470, removing the timer after 2 retriesjava.lang.StringIndexOutOfBoundsException: String index out of range: 6 at java.lang.String.substring(String.java:1963) at com.drajer.cda.utils.CdaGeneratorUtils.getXmlForTelecom(CdaGeneratorUtils.java:647) at com.drajer.cdafromr4.CdaFhirUtilities.getTelecomXml(CdaFhirUtilities.java:387) at com.drajer.cdafromr4.CdaHeaderGenerator.getPatientDetails(CdaHeaderGenerator.java:699) at com.drajer.cdafromr4.CdaHeaderGenerator.createCdaHeader(CdaHeaderGenerator.java:120) at com.drajer.cdafromr4.CdaEicrGeneratorFromR4.convertR4FhirBundletoCdaEicr(CdaEicrGeneratorFromR4.java:28) at com.drajer.eca.model.EcaUtils.createEicr(EcaUtils.java:171) at com.drajer.eca.model.CloseOutEicrAction.execute(CloseOutEicrAction.java:151) at com.drajer.ecrapp.service.WorkflowService.executeActions(WorkflowService.java:215) at com.drajer.ecrapp.service.WorkflowService.executeActionsForType(WorkflowService.java:230) at com.drajer.ecrapp.service.WorkflowService.executeScheduledAction(WorkflowService.java:248) at com.drajer.ecrapp.config.TaskConfiguration.lambda$sampleOneTimeTask$0(TaskConfiguration.java:64) at com.github.kagkarlsson.scheduler.task.helper.Tasks$OneTimeTaskBuilder$1.executeOnce(Tasks.java:139) at com.github.kagkarlsson.scheduler.task.helper.OneTimeTask.execute(OneTimeTask.java:37) at com.github.kagkarlsson.scheduler.Scheduler$PickAndExecute.executePickedExecution(Scheduler.java:352) at com.github.kagkarlsson.scheduler.Scheduler$PickAndExecute.runButLogExceptions(Scheduler.java:328) at com.github.kagkarlsson.scheduler.concurrent.LoggingRunnable.run(LoggingRunnable.java:28) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:750)

**Comment by AnanthaKrishnaV** [comment]
Fixed with PR #378
