### ISSUE TITLE
java.lang.IllegalArgumentException: ModelResolver already specified for model http://hl7.org/fhir

### ISSUE THREAD

**Issue by stram96** [drajer-health/eCRNow#466]
Currently we have increased the db-scheduler threads to 50 and when we ran 50 parallel tasks. We are able to get the below mentioned error for 1-4 times in each iteration.

**Error:**
01/03/2023 09:52:58.779+0000 [1;31mERROR[0;39m 4907 --- [pool-1-thread-2] [35mcom.drajer.ecrapp.util.ApplicationUtils   [0;39m [75]  : Error in completing the Execution, retry in 5 minutes.
java.lang.IllegalArgumentException: ModelResolver already specified for model http://hl7.org/fhir
	at org.opencds.cqf.cql.evaluator.builder.CqlEvaluatorBuilder.withModelResolver(CqlEvaluatorBuilder.java:134)
	at org.opencds.cqf.cql.evaluator.library.LibraryProcessor.addDataProviders(LibraryProcessor.java:201)
	at org.opencds.cqf.cql.evaluator.library.LibraryProcessor.evaluate(LibraryProcessor.java:148)
	at org.opencds.cqf.cql.evaluator.expression.ExpressionEvaluator.evaluate(ExpressionEvaluator.java:199)
	at org.opencds.cqf.cql.evaluator.expression.ExpressionEvaluator.evaluate(ExpressionEvaluator.java:109)
	at com.drajer.bsa.kar.condition.FhirPathProcessor.resolveVariables(FhirPathProcessor.java:111)
	at com.drajer.bsa.kar.condition.FhirPathProcessor.evaluateExpression(FhirPathProcessor.java:64)
	at com.drajer.bsa.kar.model.BsaAction.conditionsMet(BsaAction.java:151)
	at com.drajer.bsa.kar.action.CheckTriggerCodes.process(CheckTriggerCodes.java:125)
	at com.drajer.bsa.kar.model.BsaAction.executeSubActions(BsaAction.java:169)
	at com.drajer.bsa.kar.action.ExecuteReportingActions.process(ExecuteReportingActions.java:32)
	at com.drajer.bsa.service.impl.KarProcessorImpl.applyKarForScheduledJob(KarProcessorImpl.java:259)
	at com.drajer.bsa.service.impl.KarProcessorImpl$$FastClassBySpringCGLIB$$71cc7050.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at com.drajer.bsa.service.impl.KarProcessorImpl$$EnhancerBySpringCGLIB$$bd29b675.applyKarForScheduledJob(<generated>)
	at com.drajer.bsa.scheduler.ScheduleJobConfiguration.lambda$sampleOneTimeJob$0(ScheduleJobConfiguration.java:69)
	at com.github.kagkarlsson.scheduler.task.helper.Tasks$OneTimeTaskBuilder$1.executeOnce(Tasks.java:205)
	at com.github.kagkarlsson.scheduler.task.helper.OneTimeTask.execute(OneTimeTask.java:48)
	at com.github.kagkarlsson.scheduler.ExecutePicked.executePickedExecution(ExecutePicked.java:85)
	at com.github.kagkarlsson.scheduler.ExecutePicked.run(ExecutePicked.java:68)
	at com.github.kagkarlsson.scheduler.Executor.lambda$addToQueue$0(Executor.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by nbashyam** [comment]
This will be taken up in a future sprint based on overall eCRNow priorities.

**Comment by Nikiitha** [comment]
This issue is not observed in the recent round of load test. Kindly proceed with closing the ticket
