### ISSUE TITLE
error while insert data in notification_context  table  with mysql db

### ISSUE THREAD

**Issue by skshahi** [drajer-health/eCRNow#527]
1. Currently com.drajer.bsa.model.NotificationContext  defines it's Id as below
 ```
@Id
  @GeneratedValue
  private UUID id;
```
2.  we have define this column in our liquibase script as below
  ```
- column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: notification_context_pkey
                  name: id
                  type:uuid
```

3. With the above we are getting below error:
```
**2023-06-13 09:15:14.943  WARN 39873 --- [http-nio-8081-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1366, SQLState: HY000
2023-06-13 09:15:14.943 ERROR 39873 --- [http-nio-8081-exec-5] o.h.engine.jdbc.spi.SqlExceptionHelper   : Incorrect string value: '\xE6p\x9Dp\xC1J...' for column 'id' at row 1
2023-06-13 09:15:14.959  INFO 39873 --- [http-nio-8081-exec-5] c.d.ecrapp.security.RequestMDCFilter     : Request /api/launchPatient completed for requestId 12345678 associated to correlationId null for domain null
2023-06-13 09:15:14.961 ERROR 39873 --- [http-nio-8081-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.orm.hibernate5.HibernateJdbcException: JDBC exception on Hibernate data access: SQLException for SQL [n/a]; SQL state [HY000]; error code [1366]; could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement] with root cause

java.sql.SQLException: Incorrect string value: '\xE6p\x9Dp\xC1J...' for column 'id' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)**
```
4. This  happens because  hibernate generate binary UUID ,  but liquibase defines underlying column as text/char data
so system fails while trying to insert binary data to text column.

```

CREATE TABLE `notification_context` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
```
5. this resolves the issue :-
com.drajer.bsa.model.NotificationContext

```
@Id
  @GeneratedValue
  @Type(type = "uuid-char")
  @Column(length = 36)
  private UUID id;

```
this causes hibernate treat uuid as text data. Would it be possible to go with above definition in com.drajer.bsa.model.NotificationContext hibernate entity class? for us this has two benefits :

-      liquibase and hibernate stays in sync
-      we can easily query notification_context table using text uuid data

**Comment by skshahi** [comment]
Not Relevant anymore
