### ISSUE TITLE
EcrReportCreator::getCdaR11Report - SLF4J: Failed toString() invocation on an object of type [com.drajer.bsa.ehr.service.impl.EhrFhirR4QueryServiceImpl...]

### ISSUE THREAD

**Issue by kmarx** [drajer-health/eCRNow#742]
We see this benign error for eICR CDA R11 generation:
```
06-05-2024 22:31:01.800 [db-scheduler-pool-2-thread-1] INFO  c.drajer.bsa.kar.action.CreateReport.process - Start creating report
06-05-2024 22:31:01.800 [db-scheduler-pool-2-thread-1] INFO  c.d.bsa.kar.action.EcrReportCreator.createReport -  Creating a CDA R11 Eicr Report 
SLF4J: Failed toString() invocation on an object of type [com.drajer.bsa.ehr.service.impl.EhrFhirR4QueryServiceImpl$$EnhancerBySpringCGLIB$$da4555c9]
Reported exception:
org.springframework.cglib.core.CodeGenerationException: java.lang.IllegalAccessException-->module java.base does not open java.lang to unnamed module @5ea434c8
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:558)
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:363)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:110)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108)
	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:134)
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:319)
	at org.springframework.cglib.reflect.FastClass$Generator.create(FastClass.java:65)
	at org.springframework.cglib.proxy.MethodProxy.helper(MethodProxy.java:135)
	at org.springframework.cglib.proxy.MethodProxy.init(MethodProxy.java:76)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:216)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at com.drajer.bsa.ehr.service.impl.EhrFhirR4QueryServiceImpl$$EnhancerBySpringCGLIB$$da4555c9.toString(<generated>)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:277)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:249)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:211)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:161)
	at ch.qos.logback.classic.spi.LoggingEvent.getFormattedMessage(LoggingEvent.java:293)
	at ch.qos.logback.classic.spi.LoggingEvent.prepareForDeferredProcessing(LoggingEvent.java:206)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:223)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_1(Logger.java:398)
	at ch.qos.logback.classic.Logger.info(Logger.java:583)
	at com.drajer.bsa.kar.action.EcrReportCreator.getCdaR11Report(EcrReportCreator.java:363)
	at com.drajer.bsa.kar.action.EcrReportCreator.createReport(EcrReportCreator.java:175)
	at com.drajer.bsa.kar.action.EcrReportCreator.createReport(EcrReportCreator.java:135)
	at com.drajer.bsa.kar.action.CreateReport.process(CreateReport.java:106)
	at com.drajer.bsa.kar.model.BsaAction.executeRelatedActions(BsaAction.java:245)
	at com.drajer.bsa.kar.action.CheckTriggerCodes.process(CheckTriggerCodes.java:129)
	at com.drajer.bsa.kar.model.BsaAction.executeSubActions(BsaAction.java:162)
	at com.drajer.bsa.kar.action.ExecuteReportingActions.process(ExecuteReportingActions.java:32)
	at com.drajer.bsa.service.impl.KarProcessorImpl.applyKarForScheduledJob(KarProcessorImpl.java:249)
	at com.drajer.bsa.service.impl.KarProcessorImpl$$FastClassBySpringCGLIB$$71cc7050.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.drajer.bsa.service.impl.KarProcessorImpl$$EnhancerBySpringCGLIB$$474cea2f.applyKarForScheduledJob(<generated>)
	at com.drajer.bsa.scheduler.ScheduleJobConfiguration.lambda$0(ScheduleJobConfiguration.java:58)
	at com.github.kagkarlsson.scheduler.task.helper.Tasks$OneTimeTaskBuilder$1.executeOnce(Tasks.java:211)
	at com.github.kagkarlsson.scheduler.task.helper.OneTimeTask.execute(OneTimeTask.java:52)
	at com.github.kagkarlsson.scheduler.ExecutePicked.executePickedExecution(ExecutePicked.java:85)
	at com.github.kagkarlsson.scheduler.ExecutePicked.run(ExecutePicked.java:68)
	at com.github.kagkarlsson.scheduler.FetchCandidates.lambda$run$1(FetchCandidates.java:89)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.github.kagkarlsson.scheduler.FetchCandidates.lambda$run$2(FetchCandidates.java:87)
	at com.github.kagkarlsson.scheduler.Executor.lambda$addToQueue$0(Executor.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalAccessException: module java.base does not open java.lang to unnamed module @5ea434c8
	at java.base/java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:259)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:554)
	... 62 more
```

Code:
```
  public Bundle getCdaR11Report(
      KarProcessingData kd,
      EhrQueryService ehrService,
      String dataRequirementId,
      String profile,
      BsaAction act) {

    // Create the report as needed by the Ecr FHIR IG
    Bundle returnBundle = new Bundle();
    returnBundle.setId(UUID.randomUUID().toString());
    returnBundle.setType(BundleType.DOCUMENT);
    returnBundle.setMeta(ActionUtils.getMeta(DEFAULT_VERSION, profile));
    returnBundle.setTimestamp(Date.from(Instant.now()));
    logger.info("Ehr Query Service :{}", ehrService);
```

Not sure if related or not, but many of our test cases use this immediately reportable concept:

```
<value xsi:type="CD" code="772151004" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMED-CT" displayName="Anthrax suspected (situation)"></value>
```

**Comment by nbashyam** [comment]
Ken- anyway you can attach the loading queries and the trigger queries?

**Comment by mmatiasalt** [comment]
@kmarx are you able to attach loading/trigger queries as per Nagesh's request above? Thanks.

**Comment by mmatiasalt** [comment]
@kmarx following up to see if you are able to attach loading/trigger queries for Nagesh and Team to review?

**Comment by mmatiasalt** [comment]
@kmarx following up to see if you have loading/trigger queries for the app team to review? Thank you.

**Comment by mmatiasalt** [comment]
@kmarx touching base one last time - are you able to share loading/trigger queries for the team to review? Thank you.

**Comment by nbashyam** [comment]
Cannot reproduce.
